### ISSUE TITLE
settings not saved

### ISSUE THREAD

**Issue by elabjer** [seasonyuu/Xposed-NetworkSpeedIndicator#11]
On OnePlus 6, OOS 5.1.9 [A8.1] settings/modifications are not saved.. after each reboot they reset

**Comment by seasonyuu** [comment]
sorry about that, I have no time to make it to fit FBE

**Comment by pedropesce** [comment]
Oneplus 6, OxygenOS 5.1.11 and I have the same issue. Settings are saved in the app, but the indicator ignores them until I change each particular setting.
