### ISSUE TITLE
not working. 

### ISSUE THREAD

**Issue by iammanpreetsachdeva** [seasonyuu/Xposed-NetworkSpeedIndicator#2]
everything is correct. but it isn't working or showing up

**Comment by seasonyuu** [comment]
Which rom are you using now? and device? build.prop?

**Comment by iammanpreetsachdeva** [comment]
OnePlus X. 
Stock Rom 6.0.1
Rooted. 
TWRP Recovery
I uploaded the pdf of build prop. I don't know what is the correct way to share this thing.
[build.prop.pdf](https://github.com/seasonyuu/Xposed-NetworkSpeedIndicator/files/1589132/build.prop.pdf)

**Comment by seasonyuu** [comment]
It's seems that everything is right, which version of xposed are you using now ?

**Comment by iammanpreetsachdeva** [comment]
xposed framework version 89 is active.

**Comment by iammanpreetsachdeva** [comment]
Leave it.... it's not a big issue for me..... but thanks for your help.

**Comment by seasonyuu** [comment]
Emm.... I really want to know why it doesn't work on your device... But I don't have any OnePlus X device ..
