### ISSUE TITLE
Does not work on Oreo

### ISSUE THREAD

**Issue by MarcinOrlowski** [seasonyuu/Xposed-NetworkSpeedIndicator#6]
Hi

I recently upgraded from Marshmallow to Oreo and it seems your extension is not compatible with that version as it shows nothing (it does not crash though)

**Comment by seasonyuu** [comment]
What version of my module are you using?

**Comment by MarcinOrlowski** [comment]
2.7.0. No newer version shown by Xposer Installer

**Comment by seasonyuu** [comment]
I hadn't post it to Xposed Installer, you can download the v2.7.1 in the release page, it should work on Oreo

**Comment by reza-patel** [comment]
Can you point me to the release page? I've been facing issue where it shows when the phone starts but disappears in a while. Disabling and enabling it again brings it back. Currently on 2.7.0. Thanks

**Comment by seasonyuu** [comment]
@reza-patel you can download this module in Xposed Installer

**Comment by reza-patel** [comment]
The latest version on Xposed is 2.7.0 whereas you mentioned the latest is 2.7.1 on this thread. Was wondering if the new version would fix the issue of the meter disappearing a few mins after restart of the phone.

**Comment by seasonyuu** [comment]
https://github.com/seasonyuu/Xposed-NetworkSpeedIndicator/releases @reza-patel But I'm not sure what problem you are facing ... By the way, what's your device and ROM?

**Comment by reza-patel** [comment]
@seasonyuu OnePlus 6 latest OOS. The module executes and shows the network meter but in a matter of minutes (maybe after a few screen offs and ons) the meter stops showing. All other Xposed modules (Gravitybox) continue to work as normal. Will try out the 2.7.1. Thanks!

**Comment by reza-patel** [comment]
Almost 15 hours and everything seems to be working great on 2.7.1. Thank you!
