### ISSUE TITLE
一加6上运行好像有问题

### ISSUE THREAD

**Issue by mlch911** [seasonyuu/Xposed-NetworkSpeedIndicator#7]
最开始的时候没问题，后来成砖了，重新恢复后怎么都不行，状态栏不会显示。除了内置存储其他都已经清空了，是不是有什么本地的文件出问题了？？？

**Comment by seasonyuu** [comment]
一加 6 … 厉害了…… Xposed 的问题，你下次遇到这个应该去刷一个 Xposed Uninstaller 再看看
